/* Generated by updaterev.sh, do not edit */
#ifdef SDL_VENDOR_INFO
#define SDL_REVISION "SDL-release-2.30.2-0-gf461d91cd (" SDL_VENDOR_INFO ")"
#else
#define SDL_REVISION "SDL-release-2.30.2-0-gf461d91cd"
#endif
#define SDL_REVISION_NUMBER 0
