//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SysDVRClientGUI.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SysDVRClientGUI.Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done.
        /// </summary>
        internal static string DONE {
            get {
                return ResourceManager.GetString("DONE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading.
        /// </summary>
        internal static string DOWNLOADING {
            get {
                return ResourceManager.GetString("DOWNLOADING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Driver.
        /// </summary>
        internal static string DRIVER {
            get {
                return ResourceManager.GetString("DRIVER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Driver download and extraction failed.
        /// </summary>
        internal static string DRIVERINSTALL_EXTRACT_FAILED {
            get {
                return ResourceManager.GetString("DRIVERINSTALL_EXTRACT_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Driver installation failed.
        /// </summary>
        internal static string DRIVERINSTALL_FAILED {
            get {
                return ResourceManager.GetString("DRIVERINSTALL_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \r\n\r\nRestart this application and try again, if it keeps on happening open an issue on GitHub.\r\nYou can also try following the manual driver installation guide on GitHub.
        /// </summary>
        internal static string DRIVERINSTALL_FORM_ERRORMESSAGE {
            get {
                return ResourceManager.GetString("DRIVERINSTALL_FORM_ERRORMESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This page allows you to install the USB driver.
        ///Since version 5.5 SysDVR uses the standard Android driver provided by Google.
        ///
        ///If you click install this setup will download latest driver provided by Google from the official link and prompt to install it
        ///This operation requires an internet connection.
        /// </summary>
        internal static string DRIVERINSTALL_FORM_INFOTEXT {
            get {
                return ResourceManager.GetString("DRIVERINSTALL_FORM_INFOTEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The correct driver seems to be already installed, you don&apos;t need to install it again..
        /// </summary>
        internal static string DRIVERINSTALL_FORM_INSTALLED_ALREADY {
            get {
                return ResourceManager.GetString("DRIVERINSTALL_FORM_INSTALLED_ALREADY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It seems the driver is already installed, unless you face issues, you DON&apos;T need to install it again..
        /// </summary>
        internal static string DRIVERINSTALL_FORM_INSTALLED_ALREADY_INFO {
            get {
                return ResourceManager.GetString("DRIVERINSTALL_FORM_INSTALLED_ALREADY_INFO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It seems Windows has never detected the SysDVR device ID, enable USB mode in SysDVR-Settings and connect your console. Note that USB-C to C cables may not work..
        /// </summary>
        internal static string DRIVERINSTALL_FORM_NOT_DETECTED {
            get {
                return ResourceManager.GetString("DRIVERINSTALL_FORM_NOT_DETECTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It seems the driver is not installed, you need to install it to use SysDVR..
        /// </summary>
        internal static string DRIVERINSTALL_FORM_NOT_INSTALLED {
            get {
                return ResourceManager.GetString("DRIVERINSTALL_FORM_NOT_INSTALLED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string ERROR {
            get {
                return ResourceManager.GetString("ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        internal static string EXIT {
            get {
                return ResourceManager.GetString("EXIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install.
        /// </summary>
        internal static string INSTALL {
            get {
                return ResourceManager.GetString("INSTALL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installing.
        /// </summary>
        internal static string INSTALLING {
            get {
                return ResourceManager.GetString("INSTALLING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Launch.
        /// </summary>
        internal static string LAUNCH {
            get {
                return ResourceManager.GetString("LAUNCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to will now close.
        /// </summary>
        internal static string WILL_CLOSE_NOW {
            get {
                return ResourceManager.GetString("WILL_CLOSE_NOW", resourceCulture);
            }
        }
    }
}
